version: "3.6"

networks:
  app-tier:
    driver: bridge

services:
  front:
    stdin_open: true
    container_name: front_container
    build:
      dockerfile: Dockerfile
      context: ./front
    # networks:
    #   - app-tier
    volumes:
      - /app/node_modules
      - ./front:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
