version: "3.6"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - app-network

  back:
    depends_on:
      - mongodb
    container_name: back_container
    build:
      dockerfile: Dockerfile
      context: "./back"
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$PORT
    environment:
      - PORT=$PORT
      - DB_HOST=$MONGODB_HOST
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - DB_URL=$MONGODB_URL
      - DB_CLOUD=$MONGODB_CLOUD
    stdin_open: true
    tty: true
    networks:
      - app-network

  front:
    stdin_open: true
    container_name: front_container
    build:
      dockerfile: Dockerfile
      context: ./front
    volumes:
      - /app/node_modules
      - ./front:/var/www/html
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  nginx:
    depends_on:
      - back
      - front
    container_name: nginx_container
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  db:

#Docker Networks
networks:
  app-network:
    driver: bridge